{
    "label": "SnarkMedX",
    "devmode": 1,
    "after_cab_fan_on_pause": 1,
    "after_hot_fan_on_pause": 1,
    "pid1": 600,
    "after_pid1_pause": 1,
    "pid2": 400,
    "after_pid2_pause": 1,
    "after_aux1_close_pause": 1,
    "after_radiator_on_pause": 1,
    "after_vent_open_pause": 1,
    "after_vac_on_pause": 1,
    "cooldown1": 180,
    "cooldown2": 600,
    "after_hot_fan_pause": 1,
    "after_vac_off_pause": 1,
    "after_cooling_vent_close_pause": 1,
    "after_radiator_off_pause": 12,
    "after_chamber_open_pause": 1
}